#include <SDL2/SDL_opengl.h>
#include <SDL2/SDL.h>

void test() {
    PFNGLGENFRAMEBUFFERSEXTPROC a;
    PFNGLBINDFRAMEBUFFEREXTPROC b;
    PFNGLFRAMEBUFFERTEXTURE2DEXTPROC c;
    PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC d;
    PFNGLDELETEFRAMEBUFFERSEXTPROC e;
}
